<div id="healthlab-information-modal" style="width : 100%">
    <div class="custom-header">
        <div class="header-title">
            <p class="fs-30px color-white"><?= $block->escapeHtml(__('Stay informed for a')) ?></p>
            <h5 class="fs-50px color-white hvdtrial"><?= $block->escapeHtml(__('Healthier you')) ?></h5>
        </div>
        <button class="btn-mealplan-close">
            <img src="<?= $block->escapeUrl($this->getViewFileUrl('Annam_HealthLab/images/icon-close.svg')) ?>" alt="icon-close.svg">
        </button>
    </div>
    <div class="container-modal">

        <form class="form" id="create-form" method="post" data-mage-init='{"validation":{}}'>

            <fieldset class="fieldset">
                <div class="field information-firstname required">
                    <label class="label" for="information-firstname"><span><?= __('Name') ?></span></label>
                    <div class="control">
                        <input placeholder="<?= __('Name')?>" name="information-firstname" id="information-firstname" title="information-firstname" value="" type="text" class="input-text required-entry"/>
                    </div>
                </div>
            </fieldset>

            <fieldset class="fieldset">
                <div class="field information-email required">
                    <label class="label" for="information-email"><span><?= __('Email') ?></span></label>
                    <div class="control">
                        <input placeholder="<?= __('Email')?>" name="information-email" id="information-email" title="information-email" value="" type="email" class="input-text required-entry"/>
                    </div>
                </div>
            </fieldset>

            <div class="actions-toolbar full-width-footer">
                <div class="primary">
                    <button id="submit-button-information-service" type="button" title="Submit" class="action submit primary">
                        <?php echo __('Submit'); ?>
                    </button>
                </div>
            </div>

            <div id="information-error-message" style="display:none; color:red;"></div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
    	"*": {
    		"Annam_HealthLab/js/sendmail-information": {}
        }
    }
</script>
