
<div class="healthlab-wishlist">
    <div class="healthlab-header header-wishlist">
        <div class="healthlab-header-box"><span></span></div>
    </div>
    <div class="wishlist-main container-content">
        <div class="wishlist-header">
            <h5><?= __('your organic') ?></h5>
            <h4><?= __('wishlist') ?></h4>
            <div class="wishlist-filter">
                <div class="healthlab-wishlist-sort">
                    <label for="wishlist-sort"></label>
                    <select id="wishlist-sort">
                        <option value="name" selected="selected"><?= $block->escapeHtml(__("Product Name")) ?></option>
                        <option value="price"><?= $block->escapeHtml(__("Price")) ?></option>
                        <option value="weight"><?= $block->escapeHtml(__("Weight")) ?></option>
                    </select>
                </div>

                <button class="wishlist-sort-by" data-value="asc">
                    <img src="<?= $block->escapeUrl($this->getViewFileUrl('Annam_HealthLab/images/filter-icon/filter-asc.svg')) ?>" alt="asc-icon">
                </button>
            </div>

        </div>
        <ul class="wishlist-list"></ul>
        <div class="wishlist-footer">
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
    	"*": {
    		"Annam_HealthLab/js/page-wishlist": {
    		}
    	}
    }
</script>
