<div id="modal-touchme">
    <div class="modal-body-content-touchme">
        <div class="container-touchme">
            <button class="btn-touchme"></button>
            <img src="<?= $block->escapeUrl($this->getViewFileUrl('Annam_HealthLab/images/touchme-banner.png')) ?>" alt="banner-touchme">
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
    	"*": {
    		"Annam_HealthLab/js/touchme": {}
        }
    }
</script>
